backend:
  name: git-gateway
  branch: master

media_folder: static/assets
public_folder: /assets

collections:    
  - name: 'section'
    label: 'Section'
    editor:
      preview: false
    files:
      - file: 'content/metadata.md'
        label: 'Metadata'
        name: 'metadata'
        fields:
          - {
              label: 'Template Key',
              name: 'templateKey',
              widget: 'hidden',
              default: 'metadata'
            }
          - { label: 'Title', name: 'title', widget: 'string' }
          - { label: 'Subtitle', name: 'subtitle', widget: 'string' }
          - { label: 'Description', name: 'description', widget: 'text' }
          - { label: 'Image', name: 'image', widget: 'image' }
          - { label: 'Logo', name: 'logo', widget: 'image' }
          - { label: 'Instagram', name: 'instagram', widget: 'string', required: false }
          - { label: 'Facebook', name: 'facebook', widget: 'string', required: false }
          - { label: 'Tél', name: 'tel', widget: 'string', required: false }          
          - { label: 'Email', name: 'email', widget: 'string', required: false }
          - { label: 'Adresse', name: 'address', widget: 'string', required: false }         
      - file: 'content/intro.md'
        label: 'Intro'
        name: 'intro'
        fields:
          - {
              label: 'Template Key',
              name: 'templateKey',
              widget: 'hidden',
              default: 'intro'
            }
          - { label: 'Title', name: 'title', widget: 'string' }
          - { label: 'Sous-titre', name: 'subtitle', widget: 'text', required: false }
          - { label: 'Texte', name: 'body', widget: 'markdown', required: false }
      - file: 'content/aperitifs.md'
        label: 'Apéritifs'
        name: 'aperitifs'
        fields:
          - {
              label: 'Template Key',
              name: 'templateKey',
              widget: 'hidden',
              default: 'aperitifs'
            }
          - { label: 'Title', name: 'title', widget: 'string' }
          - { label: 'Sous-titre', name: 'subtitle', widget: 'text', required: false }
          - { label: 'Menu',
              name: 'menu',
              widget: 'list',
              fields:
                [
                  { label: 'Titre', name: 'title', widget: 'string' },
                  { label: 'Image', name: 'image', widget: 'image' },
                  { label: 'Plats', name: 'plats', widget: 'list', fields:
                    [
                      { label: 'Plat', name: 'plat', widget: 'string' }
                    ] 
                  }
                ]
            }            
      - file: 'content/buffets.md'
        label: 'Buffets'
        name: 'buffets'
        fields:
          - {
              label: 'Template Key',
              name: 'templateKey',
              widget: 'hidden',
              default: 'buffets'
            }
          - { label: 'Title', name: 'title', widget: 'string' }
          - { label: 'Sous-titre', name: 'subtitle', widget: 'text', required: false }
          - { label: 'Menu',
              name: 'menu',
              widget: 'list',
              fields:
                [
                  { label: 'Titre', name: 'title', widget: 'string' },
                  { label: 'Image', name: 'image', widget: 'image' },
                  { label: 'Plats', name: 'plats', widget: 'list', fields:
                    [
                      { label: 'Plat', name: 'plat', widget: 'string' }
                    ] 
                  }
                ]
            }            
      - file: 'content/biographie.md'
        label: 'Bio'
        name: 'biographie'
        fields:
          - {
              label: 'Template Key',
              name: 'templateKey',
              widget: 'hidden',
              default: 'biographie'
            }
          - { label: 'Titre', name: 'title', widget: 'string' }
          - { label: 'Sous-titre', name: 'subtitle', widget: 'text' }
          - { label: 'Texte', name: 'body', widget: 'markdown', required: false }
          - { label: 'Image', name: 'image', widget: 'image', required: false }
      - file: 'content/references.md'
        label: 'Références'
        name: 'references'
        fields:
          - {
              label: 'Template Key',
              name: 'templateKey',
              widget: 'hidden',
              default: 'references'
            }
          - { label: 'Title', name: 'title', widget: 'string' }
          - { label: 'Sous-titre', name: 'subtitle', widget: 'text', required: false }
          - { label: 'Texte', name: 'body', widget: 'markdown', required: false }
          - { label: 'Client logo',
              name: 'logos',
              widget: 'list',
              fields:
                [
                  { label: 'Image', name: 'image', widget: 'image' }
                ]
            }   
          - { label: 'Image', name: 'image', widget: 'image', required: false } 
          
  - name: 'posts'
    label: 'Prestation'
    folder: 'content/posts'
    editor:
      preview: false    
    create: true
    slug: '{{slug}}'
    fields:
      - {
          label: 'Template Key',
          name: 'templateKey',
          widget: 'hidden',
          default: 'post',
        }
      - { label: 'Title', name: 'title', widget: 'string' }
      - { label: 'Publish Date', name: 'date', widget: 'hidden' }
      - { label: 'Slug', name: 'slug', widget: 'string' }
      - { label: 'Texte', name: 'body', widget: 'markdown' }
      - { label: 'Menu',
            name: 'menu',
            widget: 'list',
            fields:
              [
                { label: 'Titre', name: 'title', widget: 'string' },
                { label: 'Image', name: 'image', widget: 'image' },
                { label: 'Plats', name: 'plats', widget: 'list', fields:
                  [
                    { label: 'Plat', name: 'plat', widget: 'string' }
                  ] 
                }
              ]
            }           